### ISSUE TITLE
Change website permissions 

### ISSUE THREAD

**Issue by lordlycastle** [cheluskis/hangremote#11]
Change the URL on which this extension is meant to work on is `*meet.google.com/+` (`+` because we also don't want to load it on `meet.google.com` home page) so it only needs and loads on those website. Have a look at URL regex other google meet extensions are settings.

**Comment by chelorossi** [comment]
Hi @lordlycastle,

Tested the `+` plus and does not work, breaks the script.
All the other extensions I have seen use the `*`.
On the other hand, what is the gain by not having in the homepage, the cost is insubstantial, since it is a super lightweight  scripts.


In any case, you are more than welcome to come up with a PR.
Starring is more than welcome to support the project.

Best

**Comment by lordlycastle** [comment]
Okay, Will do. I did have a reason in mind when I created this issue. I think it had to do with multiple calls open at a time. I'll try to recreate and then open PR.

Thanks for all your work!

**Comment by chelorossi** [comment]
It does not work for multiple sessions in the same chrome user (but it does
work for different chrome users at the same time, 1 session each)

Thanks for your support,
Starring in github and extensions store is more than welcome to support
this non-profit project.

Best.
